### PR TITLE
Typescript type definitions

### PR DESCRIPTION
**Pull request by mlewando**
I added type definitions to this module to be able to use it in typescript project. I based definitions on current documentation in README.md and tested it in my project.

### CODE REVIEW

**Comment by nhunzaker** [comment]
😍. Will review later tonight

**Comment by nhunzaker** [comment]
Thank you so much!

**Comment by mlewando** [comment]
tonight? you are fast! :)

**Comment by nhunzaker** [comment]
Hmm. This looks good either way. I'll send out an RC shortly. Let's continue to coordinate here.

**Comment by nhunzaker** [comment]
@mlewando can you checkout `react-ink@6.1.0-rc`? After you confirm, I'll push a full release.

**Comment by mlewando** [comment]
Checked, `react-ink@6.1.0-rc`  is working :)

**Comment by nhunzaker** [comment]
@mlewando Perfect timing. Shipped `react-ink@6.1.0`:

https://github.com/vigetlabs/react-ink/releases/tag/v6.1.0

**Comment by mlewando** [comment]
Wow, that was fast! Thank you very much

**Pull request merged**
